#language: android
#jdk: oraclejdk8
#before_install:
#- yes | sdkmanager "platforms;android-28"
#
#env:
#  global:
#    - ANDROID_API_LEVEL=28
#    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
##    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
#    - TRAVIS_SECURE_ENV_VARS=true
#
#android:
#  components:
#    # The BuildTools version used by your project
#    - tools
#    - platform-tools
#    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
#    - extra-android-m2repository
#    - extra-google-android-support
#
#    # The SDK version used to compile your project
#    - android-$ANDROID_API_LEVEL
#  licenses:
#    - '.+'
#
#script:
#    - ./gradlew clean
##    - ./gradlew install
##    - ./gradlew bintrayUpload
#    - ./gradlew assembleDebug


language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-29.0.2
    # The SDK version used to compile your project
    - android-29
    # Android support Repository
    - extra-android-m2repository
    # Support Library
#    - extra-android-m2repository-com-android-support
script:
  # 生成APK
#  - ./gradlew clean
  #    - ./gradlew install
  #    - ./gradlew bintrayUpload
#  - ./gradlew assembleDebug
  -  chmod +x gradlew
  - ./gradlew assembleRelease

before_deploy:     # 部署之前
  # 使用 mv 命令进行修改 apk 文件的名字
  - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/buff.apk

#部署
deploy:
  #部署到github release
  #此外Travis CI还支持发布到fir.im、AWS、Google App Engine
  provider: releases
  #Github oauth token
  api_key: "$GIT_TOKEN"
  #部署文件路径：对于Android就部署生成的apk文件
  file:
    - app/build/outputs/apk/release/buff.apk
  #避免Travis在部署清空生成的apk文件
  skip_cleanup: true
  #发布时机
  on:
    #tags设置为true表示只有在tag的情况下才部署
    tags: true
    branch:  master
before_install:
  - chmod a+x gradlew
  - rvm install 2.1.5
  - gem install fir-cli
after_deploy:
  - fir publish app/build/outputs/apk/release/buff.apk -T $FIR_IM -c "`git cat-file tag $TRAVIS_TAG`"

notifications:
  email:
    - weijiangxing777@qq.com
