#language: android
#jdk: oraclejdk8
#before_install:
#- yes | sdkmanager "platforms;android-28"
#
#env:
#  global:
#    - ANDROID_API_LEVEL=28
#    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
##    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
#    - TRAVIS_SECURE_ENV_VARS=true
#
#android:
#  components:
#    # The BuildTools version used by your project
#    - tools
#    - platform-tools
#    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
#    - extra-android-m2repository
#    - extra-google-android-support
#
#    # The SDK version used to compile your project
#    - android-$ANDROID_API_LEVEL
#  licenses:
#    - '.+'
#
#script:
#    - ./gradlew clean
##    - ./gradlew install
##    - ./gradlew bintrayUpload
#    - ./gradlew assembleDebug


language: android
android:
  components:
    # The BuildTools version used by your project
#    - tools
#    - platform-tools
    - build-tools-29.0.2
    # The SDK version used to compile your project
    - android-28
    # Android support Repository
    - extra-android-m2repository
    # Support Library
#    - extra-android-support
script:
  # 生成APK
#  - ./gradlew clean
  #    - ./gradlew install
  #    - ./gradlew bintrayUpload
#  - ./gradlew assembleDebug
  - ./gradlew assembleRelease

#部署
deploy:
  #部署到github release
  #此外Travis CI还支持发布到fir.im、AWS、Google App Engine
  provider: releases
  #Github oauth token
  api_key: "$GIT_TOKEN"
  #部署文件路径：对于Android就部署生成的apk文件
  file:
    - app/release
  #避免Travis在部署清空生成的apk文件
#  skip_cleanup: true
  #发布时机
  on:
    #tags设置为true表示只有在tag的情况下才部署
    tags: true
    all_branches: true